-- MySQL Script generated by MySQL Workbench
-- 06/27/16 23:52:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema zhenghe_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zhenghe_db` ;

-- -----------------------------------------------------
-- Schema zhenghe_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zhenghe_db` DEFAULT CHARACTER SET utf8 ;
USE `zhenghe_db` ;

-- -----------------------------------------------------
-- Table `zhenghe_db`.`doctortbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhenghe_db`.`doctortbl` ;

CREATE TABLE IF NOT EXISTS `zhenghe_db`.`doctortbl` (
  `DOCTOR_UID` VARCHAR(64) NOT NULL,
  `REAL_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `PHONE_NUMBER` VARCHAR(64) NULL DEFAULT NULL,
  `PASSWORD` VARCHAR(256) NULL DEFAULT NULL,
  `GENDER` CHAR(1) NULL DEFAULT NULL,
  `LEVE` CHAR(1) NULL DEFAULT NULL,
  `AGE` INT(11) NULL DEFAULT NULL,
  `DEPARTMENT` VARCHAR(128) NULL DEFAULT NULL,
  `INSTITUTION` VARCHAR(128) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(128) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(2048) NULL DEFAULT NULL,
  PRIMARY KEY (`DOCTOR_UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhenghe_db`.`anwsertbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhenghe_db`.`anwsertbl` ;

CREATE TABLE IF NOT EXISTS `zhenghe_db`.`anwsertbl` (
  `ANWSER_UID` VARCHAR(64) NOT NULL,
  `DOCTOR_UID` VARCHAR(64) NOT NULL,
  `ANWSER_CREATE_TIME` DATETIME NOT NULL,
  `TEXT` VARCHAR(4096) NULL DEFAULT NULL,
  PRIMARY KEY (`ANWSER_UID`),
  INDEX `FK_AD` (`DOCTOR_UID` ASC),
  CONSTRAINT `FK_AD`
    FOREIGN KEY (`DOCTOR_UID`)
    REFERENCES `zhenghe_db`.`doctortbl` (`DOCTOR_UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhenghe_db`.`clinicalevaluatetbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhenghe_db`.`clinicalevaluatetbl` ;

CREATE TABLE IF NOT EXISTS `zhenghe_db`.`clinicalevaluatetbl` (
  `EVALUATION_UID` VARCHAR(64) NOT NULL,
  `PATIENT_UID` VARCHAR(64) NULL DEFAULT NULL,
  `EVALUATION` VARCHAR(8192) NULL DEFAULT NULL,
  `EVALUATION_TIME` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`EVALUATION_UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhenghe_db`.`evaluationfiletbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhenghe_db`.`evaluationfiletbl` ;

CREATE TABLE IF NOT EXISTS `zhenghe_db`.`evaluationfiletbl` (
  `FILE_UID` VARCHAR(64) NOT NULL,
  `NAME` VARCHAR(256) NULL DEFAULT NULL,
  `PATH` VARCHAR(2048) NULL DEFAULT NULL,
  `FILE_TYPE` VARCHAR(16) NULL DEFAULT NULL,
  `FILE_USAGE` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`FILE_UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhenghe_db`.`evaluationfilerelationtbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhenghe_db`.`evaluationfilerelationtbl` ;

CREATE TABLE IF NOT EXISTS `zhenghe_db`.`evaluationfilerelationtbl` (
  `EVALUATION_UID` VARCHAR(64) NULL DEFAULT NULL,
  `FILE_UID` VARCHAR(64) NULL DEFAULT NULL,
  INDEX `FK_CEF1` (`EVALUATION_UID` ASC),
  INDEX `FK_CEF2` (`FILE_UID` ASC),
  CONSTRAINT `FK_CEF1`
    FOREIGN KEY (`EVALUATION_UID`)
    REFERENCES `zhenghe_db`.`clinicalevaluatetbl` (`EVALUATION_UID`),
  CONSTRAINT `FK_CEF2`
    FOREIGN KEY (`FILE_UID`)
    REFERENCES `zhenghe_db`.`evaluationfiletbl` (`FILE_UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhenghe_db`.`patienttbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhenghe_db`.`patienttbl` ;

CREATE TABLE IF NOT EXISTS `zhenghe_db`.`patienttbl` (
  `PATIENT_UID` VARCHAR(64) NOT NULL,
  `REAL_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `PASSWORD` VARCHAR(32) NULL DEFAULT NULL,
  `NATION` VARCHAR(16) NULL DEFAULT NULL,
  `PHONE_NUMBER` VARCHAR(64) NULL DEFAULT NULL,
  `GENDER` CHAR(1) NULL DEFAULT NULL,
  `MARRIAGE` CHAR(1) NULL DEFAULT NULL,
  `AGE` INT(11) NULL DEFAULT NULL,
  `HEIGTH` INT(11) NULL DEFAULT NULL,
  `WEIGTH` INT(11) NULL DEFAULT NULL,
  `PROFESSION` VARCHAR(256) NULL DEFAULT NULL,
  `ADDRESS` VARCHAR(256) NULL DEFAULT NULL,
  `ALLERGY` VARCHAR(256) NULL DEFAULT NULL,
  `DISEASE` VARCHAR(512) NULL DEFAULT NULL,
  `FAMILY_DISEASE` VARCHAR(512) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(2048) NULL DEFAULT NULL,
  `SOCIAL_SECURITY_NUMBER` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`PATIENT_UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhenghe_db`.`questiontbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhenghe_db`.`questiontbl` ;

CREATE TABLE IF NOT EXISTS `zhenghe_db`.`questiontbl` (
  `QUESTION_UID` VARCHAR(64) NOT NULL,
  `PATIENT_UID` VARCHAR(64) NOT NULL,
  `QUESTION_CREATE_TIME` DATETIME NOT NULL,
  `NAME` VARCHAR(256) NULL DEFAULT NULL,
  `TEXT` VARCHAR(4096) NULL DEFAULT NULL,
  PRIMARY KEY (`QUESTION_UID`),
  INDEX `FK_QP` (`PATIENT_UID` ASC),
  CONSTRAINT `FK_QP`
    FOREIGN KEY (`PATIENT_UID`)
    REFERENCES `zhenghe_db`.`patienttbl` (`PATIENT_UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhenghe_db`.`filetbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhenghe_db`.`filetbl` ;

CREATE TABLE IF NOT EXISTS `zhenghe_db`.`filetbl` (
  `ANWSER_UID` VARCHAR(64) NULL DEFAULT NULL,
  `QUESTION_UID` VARCHAR(64) NULL DEFAULT NULL,
  `NAME` VARCHAR(256) NULL DEFAULT NULL,
  `PATH` VARCHAR(2048) NULL DEFAULT NULL,
  `FILE_TYPE` CHAR(1) NULL DEFAULT NULL,
  INDEX `FK_PA` (`ANWSER_UID` ASC),
  INDEX `FK_PQ` (`QUESTION_UID` ASC),
  CONSTRAINT `FK_PA`
    FOREIGN KEY (`ANWSER_UID`)
    REFERENCES `zhenghe_db`.`anwsertbl` (`ANWSER_UID`),
  CONSTRAINT `FK_PQ`
    FOREIGN KEY (`QUESTION_UID`)
    REFERENCES `zhenghe_db`.`questiontbl` (`QUESTION_UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhenghe_db`.`materialtbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhenghe_db`.`materialtbl` ;

CREATE TABLE IF NOT EXISTS `zhenghe_db`.`materialtbl` (
  `PATIENT_UID` VARCHAR(64) NULL DEFAULT NULL,
  `DOCTOR_UID` VARCHAR(64) NULL DEFAULT NULL,
  `NAME` VARCHAR(256) NULL DEFAULT NULL,
  `PATH` VARCHAR(2048) NULL DEFAULT NULL,
  `FILE_TYPE` CHAR(1) NULL DEFAULT NULL,
  INDEX `FK_MD` (`DOCTOR_UID` ASC),
  INDEX `FK_MP` (`PATIENT_UID` ASC),
  CONSTRAINT `FK_MD`
    FOREIGN KEY (`DOCTOR_UID`)
    REFERENCES `zhenghe_db`.`doctortbl` (`DOCTOR_UID`),
  CONSTRAINT `FK_MP`
    FOREIGN KEY (`PATIENT_UID`)
    REFERENCES `zhenghe_db`.`patienttbl` (`PATIENT_UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhenghe_db`.`patientdoctorrelationtbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhenghe_db`.`patientdoctorrelationtbl` ;

CREATE TABLE IF NOT EXISTS `zhenghe_db`.`patientdoctorrelationtbl` (
  `PATIENT_UID` VARCHAR(64) NULL DEFAULT NULL,
  `DOCTOR_UID` VARCHAR(64) NULL DEFAULT NULL,
  `RELATION_TYPE` CHAR(1) NULL DEFAULT NULL,
  INDEX `FK_PD1` (`PATIENT_UID` ASC),
  INDEX `FK_PD2` (`DOCTOR_UID` ASC),
  CONSTRAINT `FK_PD1`
    FOREIGN KEY (`PATIENT_UID`)
    REFERENCES `zhenghe_db`.`patienttbl` (`PATIENT_UID`),
  CONSTRAINT `FK_PD2`
    FOREIGN KEY (`DOCTOR_UID`)
    REFERENCES `zhenghe_db`.`doctortbl` (`DOCTOR_UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhenghe_db`.`questionanwserrelationtbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhenghe_db`.`questionanwserrelationtbl` ;

CREATE TABLE IF NOT EXISTS `zhenghe_db`.`questionanwserrelationtbl` (
  `ANWSER_UID` VARCHAR(64) NULL DEFAULT NULL,
  `QUESTION_UID` VARCHAR(64) NULL DEFAULT NULL,
  INDEX `FK_QA1` (`QUESTION_UID` ASC),
  INDEX `FK_QA2` (`ANWSER_UID` ASC),
  CONSTRAINT `FK_QA1`
    FOREIGN KEY (`QUESTION_UID`)
    REFERENCES `zhenghe_db`.`questiontbl` (`QUESTION_UID`),
  CONSTRAINT `FK_QA2`
    FOREIGN KEY (`ANWSER_UID`)
    REFERENCES `zhenghe_db`.`anwsertbl` (`ANWSER_UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zhenghe_db`.`questiondoctorrelationtbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zhenghe_db`.`questiondoctorrelationtbl` ;

CREATE TABLE IF NOT EXISTS `zhenghe_db`.`questiondoctorrelationtbl` (
  `DOCTOR_UID` VARCHAR(64) NULL DEFAULT NULL,
  `QUESTION_UID` VARCHAR(64) NULL DEFAULT NULL,
  `ANWSER_TYPE` CHAR(1) NULL DEFAULT NULL,
  INDEX `FK_QD1` (`QUESTION_UID` ASC),
  INDEX `FK_QD2` (`DOCTOR_UID` ASC),
  CONSTRAINT `FK_QD1`
    FOREIGN KEY (`QUESTION_UID`)
    REFERENCES `zhenghe_db`.`questiontbl` (`QUESTION_UID`),
  CONSTRAINT `FK_QD2`
    FOREIGN KEY (`DOCTOR_UID`)
    REFERENCES `zhenghe_db`.`doctortbl` (`DOCTOR_UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
